version: '2'
services:
    plex:
        image: plexinc/pms-docker
        container_name: plex
        ports:
            - 32400:32400
        volumes:
            - /storage/Movies:/movies
            - /storage/TV Shows:/tv
            - /storage/Home Videos:/homevideos
            - /docker/containers/plex/transcode:/transcode
            - /docker/containers/plex/config:/config
            - /docker/containers/shared:/shared
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
            - TZ="Europe/London"
            - HOSTNAME="Docker Plex"
            - PLEX_CLAIM=${PLEX_CLAIM}
            - ADVERTISE_IP="http://192.168.0.16:32400/"
        networks:
            - traefik_proxy
        labels:
            - traefik.enable=true
            - traefik.backend=plexms
            - traefik.frontend.rule=Host:plex.${DOMAINNAME}
            - traefik.port=32400
            - traefik.protocol=http
            - traefik.docker.network=traefik_proxy
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.frontend.headers.STSSeconds=315360000
            - traefik.frontend.headers.browserXSSFilter=true
            - traefik.frontend.headers.contentTypeNosniff=true
            - traefik.frontend.headers.forceSTSHeader=true
            - traefik.frontend.headers.SSLHost=EXAMPLE.COM
            - traefik.frontend.headers.STSIncludeSubdomains=true
            - traefik.frontend.headers.STSPreload=true
            - traefik.frontend.headers.frameDeny=true
    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        ports:
            - 6789:6789
        volumes:
            - /storage/Movies:/movies
            - /storage/TV Shows:/tv
            - /docker/downloads:/downloads
            - /docker/containers/nzbget/config:/config
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        ports:
            - 8989:8989
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /storage/TV Shows:/tv
            - /docker/downloads/completed/TV:/downloads/completed/TV
            - /docker/containers/sonarr/config:/config
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        ports:
            - 7878:7878
        volumes:
            - /storage/Movies:/movies
            - /docker/downloads/completed/Movies:/downloads/completed/Movies
            - /docker/containers/radarr/config:/config
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
            - TZ="Europe/London"
    handbrake:
        image: coppit/handbrake
        container_name: handbrake
        cap_add:
            - SYS_NICE
        volumes:
            - /docker/containers/handbrake/watch:/watch:ro
            - /docker/containers/handbrake/output:/output:rw
            - /docker/containers/handbrake/config:/config:rw
        restart: always
    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
    tautulli:
        image: linuxserver/tautulli
        container_name: tautulli
        ports:
            - 8181:8181
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/containers/tautulli/config:/config
            - /docker/containers/tautulli/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
    muximux:
        image: linuxserver/muximux
        container_name: muximux
        restart: always
        ports:
            - 192.168.0.50:8081:80    
        volumes:
            - /docker/containers/muximux/config:/config
    ombi:
        container_name: ombi
        restart: always
        image: linuxserver/ombi
        volumes:
            - /docker/containers/ombi/config:/config
        ports:
            - 3579:3579
        networks:
            - traefik_proxy
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="Europe/London" 
        labels:
            - traefik.enable=true
            - traefik.backend=ombi
            - traefik.frontend.rule=Host:ombi.${DOMAINNAME}
            - traefik.port=3579
            - traefik.docker.network=traefik_proxy
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.frontend.headers.STSSeconds=315360000
            - traefik.frontend.headers.browserXSSFilter=true
            - traefik.frontend.headers.contentTypeNosniff=true
            - traefik.frontend.headers.forceSTSHeader=true
            - traefik.frontend.headers.SSLHost=EXAMPLE.COM
            - traefik.frontend.headers.STSIncludeSubdomains=true
            - traefik.frontend.headers.STSPreload=true
            - traefik.frontend.headers.frameDeny=true
    traefik:
        hostname: traefik
        image: traefik:v1.7.16
        container_name: traefik
        restart: always
        domainname: ${DOMAINNAME}
        environment:
            - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
            - CF_API_KEY=${CLOUDFLARE_API_KEY}
        networks:
            - default
            - traefik_proxy
        labels:
            - traefik.enable=true
            - traefik.backend=traefik
            - traefik.frontend.rule=Host:traefik.${DOMAINNAME}
            - traefik.port=8080
            - traefik.docker.network=traefik_proxy
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.frontend.headers.STSSeconds=315360000
            - traefik.frontend.headers.browserXSSFilter=true
            - traefik.frontend.headers.contentTypeNosniff=true
            - traefik.frontend.headers.forceSTSHeader=true
            - traefik.frontend.headers.SSLHost=EXAMPLE.COM
            - traefik.frontend.headers.STSIncludeSubdomains=true
            - traefik.frontend.headers.STSPreload=true
            - traefik.frontend.headers.frameDeny=true
            - traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /docker/containers/traefik:/etc/traefik
            - /docker/containers/shared:/shared
            - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
