version: '2'
services:
    plex:
        image: plexinc/pms-docker
        container_name: plex
        network_mode: "host"
        ports:
            - 32400:32400
        volumes:
            - /storage/Movies:/movies
            - /storage/TV Shows:/tv
            - /storage/Home Videos:/homevideos
            - /docker/containers/plex/transcode:/transcode
            - /docker/containers/plex/config:/config
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
            - TZ="Europe/London"
            - VIRTUAL_HOST=plex.htpc
    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        ports:
            - 6789:6789
        volumes:
            - /storage/Movies:/movies
            - /storage/TV Shows:/tv
            - /docker/downloads:/downloads
            - /docker/containers/nzbget/config:/config
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
            - VIRTUAL_HOST=nzbget.htpc
            - VIRTUAL_PORT=6789
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        ports:
            - 8989:8989
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /storage/TV Shows:/tv
            - /docker/downloads/completed/TV:/downloads/completed/TV
            - /docker/containers/sonarr/config:/config
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
            - VIRTUAL_HOST=sonarr.htpc
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        ports:
            - 7878:7878
        volumes:
            - /storage/Movies:/movies
            - /docker/downloads/completed/Movies:/downloads/completed/Movies
            - /docker/containers/radarr/config:/config
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
            - TZ="Europe/London"
            - VIRTUAL_HOST=radarr.htpc
    handbrake:
        image: coppit/handbrake
        container_name: handbrake
        cap_add:
            - SYS_NICE
        volumes:
            - /docker/containers/handbrake/watch:/watch:ro
            - /docker/containers/handbrake/output:/output:rw
            - /docker/containers/handbrake/config:/config:rw
        restart: always
    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
    tautulli:
        image: linuxserver/tautulli
        container_name: tautulli
        ports:
            - 8181:8181
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/containers/tautulli/config:/config
            - /docker/containers/tautulli/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
        restart: always
        environment:
            - VERSION=latest
            - PGID=1000
            - PUID=1000
            - VIRTUAL_HOST=tautulli.htpc
    muximux:
        image: linuxserver/muximux
        container_name: muximux
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - /docker/containers/muximux/config:/config
        environment:
            - VIRTUAL_HOST=muximux.htpc
    ombi:
        container_name: ombi
        restart: always
        image: linuxserver/ombi
        volumes:
            - /docker/containers/ombi/config:/config
        ports:
            - 3579:3579
        environment:
            - PUID=1000
            - PGID=1000
            - TZ="Europe/London" 

