services:
  core-keeper: 
    container_name: core-keeper
    hostname: core-keeper
    image: escaping/core-keeper-dedicated
    volumes: 
      - '$DATADIR/core-keeper/server:/home/steam/core-keeper-dedicated'
      - '$DATADIR/core-keeper/data:/home/steam/core-keeper-data'
    ports: 
      - "27015:27015/udp"
    secrets:
      - game_server_password
    networks:
      - t2_proxy
      - default
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      MAX_PLAYERS: 3
      WORLD_INDEX: 0
      WORLD_SEED: 0
      WORLD_MODE: 1
      WORLD_NAME: Ymir
      DISCORD: 1
      DISCORD_HOOK: https://discord.com/api/webhooks/1276952701845901353/vlVBr1il9GXuctQfgSrW3ZH_X76mY-HhwFim_MhFhj7uKVCIPv9yN8pk6H_Nb55rDhbx
    restart: unless-stopped
    stop_grace_period: 20s