services:
  satisfactory-server:
    container_name: satisfactory-server
    hostname: satisfactory-server
    image: wolveix/satisfactory-server:latest
    volumes:
      - '$DATADIR/satisfactory/config:/config'
    networks:
      - t2_proxy
      - default
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      MAXPLAYERS: 4
      ROOTLESS: false
      STEAMBETA: false
      TIMEOUT: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G