services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      dockervlan:
        ipv4_address: 192.168.0.225
    ports:
      - 53:53/udp
      - 67:67/udp 
      - 68:68/tcp 
      - 68:68/udp 
      - 80:80/tcp 
      - 443:443/tcp 
      - 853:853/tcp 
      - 3000:3000/tcp  
    volumes:
      - $DATADIR/adguard/conf:/opt/adguardhome/conf 
      - $DATADIR/adguard/work:/opt/adguardhome/work 
      - $DATADIR/shared/certs:/certs
