services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    #profiles: ["media", "all"]
    networks:
      - socket_proxy
      - t2_proxy
    ports:
      - "8181:8181"
    volumes:
      - $DATADIR/tautulli/config:/config
      - $DATADIR/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro # For tautulli Plex log viewer
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.tautulli-rtr.entrypoints=websecure"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.tautulli-rtr.middlewares=middlewares-ip-whitelist@file"
      # HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
